apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: gitlab-analytics 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: gitlab-analytics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: gitlab-analytics
  name: gitlab-analytics
  namespace: gitlab-analytics
spec:
  selector:
    matchLabels:
      k8s-app: gitlab-analytics
  template:
    metadata:
      labels:
        k8s-app: gitlab-analytics
    spec:
      containers:
      - name: ga-mysql
        image: aiven86/ga-mariadb:5.5.60
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_USER
          value: "ga"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "gitlab_analytics"
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      - name: gitlab-analytics
        image: aiven86/ga
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "ga"
        - name: MYSQL_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "gitlab_analytics"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      - name: ga-grafana
        image: aiven86/ga-grafana:5.1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: grafana
          protocol: TCP
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      restartPolicy: Always
      serviceAccount: gitlab-analytics
      serviceAccountName: gitlab-analytics
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data

