apiVersion: v1
kind: Service
metadata:
  name: gitlab-analytics
  namespace: gitlab-analytics
  labels:
    k8s-app: gitlab-analytics
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    nodePort: 30081
  - port: 3000
    name: grafana
    nodePort: 30082
  selector:
    k8s-app: gitlab-analytics

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gitlab-analytics
  labels:
    k8s-app: gitlab-analytics
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    k8s-app: gitlab-analytics
